FROM golang:1.23
RUN apt-get update && apt-get install -y git gcc && rm -rf /var/lib/apt/lists/*
RUN wget -O /usr/local/bin/air \
    https://github.com/air-verse/air/releases/download/v1.52.3/air_1.52.3_linux_amd64 \
    && chmod +x /usr/local/bin/air
WORKDIR /app
EXPOSE 8080
CMD ["sh", "-c", "go mod download && air"]