DROP TRIGGER IF EXISTS trg_audit_dk_project_location ON dk_project_location;
DROP TRIGGER IF EXISTS trg_audit_dk_project_bappenas_partner ON dk_project_bappenas_partner;
DROP TRIGGER IF EXISTS trg_audit_dk_project_gb_project ON dk_project_gb_project;
DROP TRIGGER IF EXISTS trg_audit_gb_project_location ON gb_project_location;
DROP TRIGGER IF EXISTS trg_audit_gb_project_institution ON gb_project_institution;
DROP TRIGGER IF EXISTS trg_audit_gb_project_bappenas_partner ON gb_project_bappenas_partner;
DROP TRIGGER IF EXISTS trg_audit_gb_project_bb_project ON gb_project_bb_project;
DROP TRIGGER IF EXISTS trg_audit_bb_project_national_priority ON bb_project_national_priority;
DROP TRIGGER IF EXISTS trg_audit_bb_project_location ON bb_project_location;
DROP TRIGGER IF EXISTS trg_audit_bb_project_bappenas_partner ON bb_project_bappenas_partner;
DROP TRIGGER IF EXISTS trg_audit_bb_project_institution ON bb_project_institution;

DROP FUNCTION IF EXISTS audit_trigger_by_column_fn();
