INSERT INTO country (name, code) VALUES
('Afghanistan', 'AFG'),
('Albania', 'ALB'),
('Algeria', 'DZA'),
('Argentina', 'ARG'),
('Australia', 'AUS'),
('Austria', 'AUT'),
('Bangladesh', 'BGD'),
('Belgium', 'BEL'),
('Brazil', 'BRA'),
('Canada', 'CAN'),
('Chile', 'CHL'),
('China', 'CHN'),
('Colombia', 'COL'),
('Denmark', 'DNK'),
('Egypt', 'EGY'),
('Finland', 'FIN'),
('France', 'FRA'),
('Germany', 'DEU'),
('Greece', 'GRC'),
('Hong Kong', 'HKG'),
('Hungary', 'HUN'),
('India', 'IND'),
('Indonesia', 'IDN'),
('Ireland', 'IRL'),
('Israel', 'ISR'),
('Italy', 'ITA'),
('Japan', 'JPN'),
('Kenya', 'KEN'),
('Malaysia', 'MYS'),
('Mexico', 'MEX'),
('Netherlands', 'NLD'),
('New Zealand', 'NZL'),
('Nigeria', 'NGA'),
('Norway', 'NOR'),
('Pakistan', 'PAK'),
('Philippines', 'PHL'),
('Poland', 'POL'),
('Portugal', 'PRT'),
('Qatar', 'QAT'),
('Russia', 'RUS'),
('Saudi Arabia', 'SAU'),
('Singapore', 'SGP'),
('South Africa', 'ZAF'),
('South Korea', 'KOR'),
('Spain', 'ESP'),
('Sweden', 'SWE'),
('Switzerland', 'CHE'),
('Thailand', 'THA'),
('Turkey', 'TUR'),
('Ukraine', 'UKR'),
('United Arab Emirates', 'ARE'),
('United Kingdom', 'GBR'),
('United States', 'USA'),
('Vietnam', 'VNM');