name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate .env & Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          envs: |
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
            VITE_APP_NAME=${{ secrets.VITE_APP_NAME }}
            CLOUDFLARE_TUNNEL_TOKEN=${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
          script: |
            git pull origin main

            # Generate .env dari GitHub Secrets
            cat > .env << EOF
            # PostgreSQL
            POSTGRES_USER=${POSTGRES_USER}
            POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            POSTGRES_DB=${POSTGRES_DB}

            # Backend
            PORT=8080
            ENV=production
            DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
            JWT_SECRET=${JWT_SECRET}
            JWT_EXPIRES_IN=${JWT_EXPIRES_IN}

            # Frontend
            VITE_API_BASE_URL=${VITE_API_BASE_URL}
            VITE_APP_NAME=${VITE_APP_NAME}

            # Cloudflare
            CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
            EOF

            # Deploy
            docker compose --profile tunnel up -d --build
            docker image prune -f
